### ISSUE TITLE
Oper Login dialogue crashes plugin

### ISSUE THREAD

**Issue by xnite** [xnite/AdiIRC-Nef2-Compatibility#1]
When pressing "Login" on the oper login form, the plugin crashes.

```
Object reference not set to an instance of an object.

Void run_oper_command(System.Object, System.EventArgs)

   at Nef2_Compatibility.Nef2_Compatibility.run_oper_command(Object sender, EventArgs args)
   at System.Windows.Forms.Control.OnVisibleChanged(EventArgs e)
   at System.Windows.Forms.Form.OnVisibleChanged(EventArgs e)
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

**Comment by xnite** [comment]
Fixed in 1.0.1 :)
